=== mmontesinoscr-commits/ligaMX-xml2/liga-mx-xml-2-master/xsd/resultados.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="jornada">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="partido" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="local" type="equipoType"/>
                            <xs:element name="visitante" type="equipoType"/>
                            <xs:element name="estadio" type="xs:string"/>
                            <xs:element name="fecha" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="liga" type="xs:string" use="required"/>
            <xs:attribute name="fecha_jornada" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="equipoType">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="goles" type="xs:integer"/>
            <xs:element name="posesion" type="xs:string" minOccurs="0"/>
            <xs:element name="tiros_al_arco" type="xs:integer" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== mmontesinoscr-commits/ligaMX-xml2/liga-mx-xml-2-master/xml/resultados.xml
<?xml version="1.0" encoding="UTF-8"?>
<jornada xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/resultados.xsd"
         liga="Liga MX"
         fecha_jornada="2026-09-27">
    <partido>
        <local>
            <nombre>Club América</nombre>
            <goles>2</goles>
            <posesion>55%</posesion>
            <tiros_al_arco>7</tiros_al_arco>
        </local>
        <visitante>
            <nombre>Chivas</nombre>
            <goles>1</goles>
            <posesion>45%</posesion>
            <tiros_al_arco>4</tiros_al_arco>
        </visitante>
        <estadio>Estadio Azteca</estadio>
        <fecha>2026-09-27</fecha>
    </partido>

    <partido>
        <local>
            <nombre>Pumas UNAM</nombre>
            <goles>1</goles>
            <posesion>50%</posesion>
            <tiros_al_arco>5</tiros_al_arco>
        </local>
        <visitante>
            <nombre>Cruz Azul</nombre>
            <goles>1</goles>
            <posesion>50%</posesion>
            <tiros_al_arco>6</tiros_al_arco>
        </visitante>
        <estadio>Estadio Olímpico Universitario</estadio>
        <fecha>2026-09-27</fecha>
    </partido>
</jornada>
